name: publish to nuget
on:
  push:
    tags:
      - v*
jobs:
  call-workflow:
    uses: colemanwm/workflows/.github/workflows/PushToPrivateNuget.yml@v3
    with:
      ProjectName: ".csproj"
      ProjectFolder: ""
    secrets:
      # This should be defined on the repo that is being pushed to the nuget feed in github, as a secret
      NUGET_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}