name: 'Deploy API to Azure APIM'
on:
  workflow_call:
    inputs:
      API_PATH:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
      AZ_APP_NAME:
        required: true
        type: string
      MAIN_SLOT_VERSION_CODE:
        required: true
        type: string
      RESOURCE_GROUP_DEV:
        required: true
        type: string
      SERVICE_NAME_DEV:
        required: true
        type: string
      RESOURCE_GROUP_PROD:
        required: true
        type: string
      SERVICE_NAME_PROD:
        required: true
        type: string
    secrets:
      NUGET_TOKEN:
        required: true
      APIM_Client_ID:
        required: true
      APIM_Tenant_ID:
        required: true
      APIM_Subscription_ID:
        required: true
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
jobs:
  configure-vars:
    runs-on: ubuntu-latest
    outputs:
      AppID: ${{ steps.saveOutputVars.outputs.AppID }}
      ReleaseVersion: ${{ steps.saveOutputVars.outputs.ReleaseVersion }}
      ServiceName: ${{ steps.saveOutputVars.outputs.ServiceName }}
      ResourceGroup: ${{ steps.saveOutputVars.outputs.ResourceGroup }}
      SpecPath: ${{ steps.saveOutputVars.outputs.SpecPath }}
      MajorVersionCode: ${{ steps.saveOutputVars.outputs.MajorVersionCode }}
      SlotName: ${{ steps.saveOutputVars.outputs.SlotName }}
    env:
      ReleaseVersionTmp: "alpha"
      MajorVersionCode: "v0"
      AppID:
      SlotName:
      ServiceName:
      ReleaseVersion:
      ResourceGroup:
      SpecPath:
    steps:
      - id: getReleaseVersion
        name: Get Release Version and Major Version Code
        run: |
          echo "ReleaseVersionTmp=${{ github.ref_name }}" | sed -E 's/v[0-9]+\.[0-9]+\.[0-9]+-*//gm;t' >> "$GITHUB_ENV"
          echo "ReleaseVersion=${{ github.ref_name }}"    | sed -E 's/v[0-9]+\.[0-9]+\.[0-9]+-*//gm;t' >> "$GITHUB_ENV"
          echo "MajorVersionCode=${{ github.ref_name }}"  | sed -E 's/\.[0-9]+\.[0-9]+-*.*//gm;t'      >> "$GITHUB_ENV"
      - name: Get RG and Service - Prod
        if: ${{ env.ReleaseVersionTmp == '' }}
        run: |
          echo "ServiceName=$${{ inputs.SERVICE_NAME_PROD }}" >> "$GITHUB_ENV"
          echo "ResourceGroup=RG-${{ inputs.RESOURCE_GROUP_PROD }}" >> "$GITHUB_ENV"
          echo "AppID=${{ inputs.APP_NAME }}-${{ env.MajorVersionCode }}" >> "$GITHUB_ENV"
      - name: Get RG and Service - uat
        if: ${{ env.ReleaseVersionTmp == 'uat' }}
        run: |
          echo "ReleaseVersion=${{ env.ReleaseVersionTmp }}" >> "$GITHUB_ENV"
          echo "ServiceName=$${{ inputs.SERVICE_NAME_DEV }}" >> "$GITHUB_ENV"
          echo "ResourceGroup=RG-${{ inputs.RESOURCE_GROUP_DEV }}" >> "$GITHUB_ENV"
          echo "AppID=${{ inputs.APP_NAME }}-${{ env.MajorVersionCode }}" >> "$GITHUB_ENV"
      - name: Get RG and Service - dev
        if: ${{ env.ReleaseVersionTmp != '' && env.ReleaseVersionTmp != 'uat' }}
        run: |
          echo "ReleaseVersion=${{ env.ReleaseVersionTmp }}" >> "$GITHUB_ENV"
          echo "ServiceName=$${{ inputs.SERVICE_NAME_DEV }}" >> "$GITHUB_ENV"
          echo "ResourceGroup=RG-${{ inputs.RESOURCE_GROUP_DEV }}" >> "$GITHUB_ENV"
          echo "AppID=${{ inputs.APP_NAME }}-${{ env.MajorVersionCode }}-${{ env.ReleaseVersionTmp }}" >> "$GITHUB_ENV"
          
      - name: Get spec path and slot name - Main Version AND (Prod or UAT)
        if: ${{ env.MajorVersionCode == inputs.MAIN_SLOT_VERSION_CODE && (env.ReleaseVersionTmp == '' || env.ReleaseVersionTmp == 'uat') }}
        run: |
          echo "SpecPath=openapi/${{ inputs.APP_NAME }}_${{ inputs.MAIN_SLOT_VERSION_CODE }}.json" >> "$GITHUB_ENV"
          echo "SlotName=production" >> "$GITHUB_ENV"
      - name: Get spec path and slot name - NOT Main Version AND (Prod or UAT)
        if: ${{ env.MajorVersionCode != inputs.MAIN_SLOT_VERSION_CODE && (env.ReleaseVersionTmp == '' || env.ReleaseVersionTmp == 'uat') }}
        run: |
          echo "SpecPath=openapi/${{ inputs.APP_NAME }}_${{ env.MajorVersionCode }}.json" >> "$GITHUB_ENV"
          echo "SlotName=${{ env.MajorVersionCode }}" >> "$GITHUB_ENV"
      - name: Get spec path and slot name - NOT Prod AND NOT UAT
        if: ${{ env.ReleaseVersionTmp != '' && env.ReleaseVersionTmp != 'uat' }}
        run: |
          echo "SpecPath=openapi/${{ inputs.APP_NAME }}_${{ env.MajorVersionCode }}-${{ env.ReleaseVersionTmp }}.json" >> "$GITHUB_ENV"
          echo "SlotName=${{ env.MajorVersionCode }}-${{ env.ReleaseVersionTmp }}" >> "$GITHUB_ENV"
      - name: Get spec path - v1 special handling AND (Prod or UAT)
        if: ${{ env.MajorVersionCode == 'v1' && (env.ReleaseVersionTmp == '' || env.ReleaseVersionTmp == 'uat') }}
        run: |
          echo "SpecPath=openapi/${{ inputs.APP_NAME }}.json" >> "$GITHUB_ENV"

      - id: saveOutputVars
        name: Save the output variables
        run: |
          echo "AppID=${{ env.AppID }}" >> "$GITHUB_OUTPUT"
          echo "ReleaseVersion=${{ env.ReleaseVersion }}" >> "$GITHUB_OUTPUT"
          echo "ServiceName=${{ env.ServiceName }}" >> "$GITHUB_OUTPUT"
          echo "ResourceGroup=${{ env.ResourceGroup }}" >> "$GITHUB_OUTPUT"
          echo "SpecPath=${{ env.SpecPath }}" >> "$GITHUB_OUTPUT"
          echo "SlotName=${{ env.SlotName }}" >> "$GITHUB_OUTPUT"
          echo "MajorVersionCode=${{ env.MajorVersionCode }}" >> "$GITHUB_OUTPUT"
      
  build:
    runs-on: windows-latest
    needs: configure-vars
    permissions:
      contents: read #This is required for actions/checkout
    env:
      NUGET_URL: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    steps:        
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'
          
      - name: Restore
        run: |
          dotnet nuget add source ${{env.NUGET_URL}} --name "github" --username someusername --password ${{secrets.NUGET_TOKEN}}
          dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore --property WarningLevel=1

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs:
      - build
      - configure-vars
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    env:
      API_NAME: ${{ inputs.APP_NAME }}
      API_PATH: ${{ inputs.API_PATH }}
      APP_ID: "${{ needs.configure-vars.outputs.AppID }}"
      AZ_APP_NAME: ${{ inputs.AZ_APP_NAME }}
      RELEASE_VERSION: "${{ needs.configure-vars.outputs.ReleaseVersion }}"
      RESOURCE_GROUP: "${{ needs.configure-vars.outputs.ResourceGroup }}"
      SERVICE_NAME: "${{ needs.configure-vars.outputs.ServiceName }}"
      SLOT_NAME: "${{ needs.configure-vars.outputs.SlotName }}"
      SPEC_PATH: "${{ needs.configure-vars.outputs.SpecPath }}"
      SERVICE_URL: "DEFAULT"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APIM_Client_ID }}
          tenant-id: ${{ secrets.APIM_Tenant_ID }}
          subscription-id: ${{ secrets.APIM_Subscription_ID }}
      - name: Get service URL
        run: |
          $apiList = az apim api list -g ${{ env.RESOURCE_GROUP }} -n ${{ env.SERVICE_NAME }} | Convertfrom-json
          $filteredList = $apiList | Where-Object name -eq ${{ env.APP_ID }}
          echo "SERVICE_URL=$filteredList.serviceURL" >> "$GITHUB_ENV"

      - name: Deploy to Azure Web App
        if: ${{ env.SERVICE_URL != 'DEFAULT' }}
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "${{ env.AZ_APP_NAME }}"
          slot-name: "${{ env.SLOT_NAME }}"
          package: .
          
      - name: Update APIM APIs
        if: ${{ env.SERVICE_URL != 'DEFAULT' }}
        run: az apim api import --resource-group "${{ env.RESOURCE_GROUP }}" --service-name "${{ env.SERVICE_NAME }}" --path "${{ env.API_PATH }}" --serivce-url ${{ env.SERVICE_URL }} --specification-format OpenApiJson --specification-path "${{ env.SPEC_PATH }}" --api-id "${{ env.APP_ID }}"
