name: 'Deploy API to Azure APIM'
on:
  workflow_call:
    inputs:
      AZ_APP_NAME:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
      RESOURCE_GROUP:
        required: true
        type: string
      SERVICE_NAME:
        required: true
        type: string
      API_PATH:
        required: true
        type: string
    secrets:
      NUGET_TOKEN:
        required: true
      APIM_Client_ID:
        required: true
      APIM_Tenant_ID:
        required: true
      APIM_Subscription_ID:
        required: true
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
jobs:
  configure-vars:
    runs-on: ubuntu-latest
    outputs:
      FormattedCode: ${{ steps.storeVersionCode.outputs.FormattedCode }}
      SpecPath: ${{ steps.storeSpecPath.outputs.SPEC_PATH }}
      AppID: ${{ steps.storeAppID.outputs.APP_ID }}
    env:
      APP_NAME: $${{ inputs.APP_NAME }}
    steps:
      - name: Get Version Code (env)
        run: |
          echo "FormattedCode=${{ github.ref_name }}" | sed -e "s#releases/##g" >> "$GITHUB_ENV"
      - name: Get spec path - non-v1 handling
        if: ${{ env.FormattedCode != 'v1' }}
        run: |
          echo "SPEC_PATH=openapi/${{ env.APP_NAME }}_${{ github.ref_name }}.json" >> "$GITHUB_ENV"
      - name: Get spec path - v1 handling
        if: ${{ env.FormattedCode == 'v1' }}
        run: |
          echo "SPEC_PATH=openapi/${{ env.APP_NAME }}.json" >> "$GITHUB_ENV"
      - id: storeVersionCode
        name: Store Version Code
        run: |
          echo "FormattedCode=${{ github.ref_name }}" | sed -e "s#releases/##g" >> "$GITHUB_OUTPUT"
      - id: storeSpecPath
        name: Store Spec Path
        run: |
          echo "SPEC_PATH=${{ env.SPEC_PATH }}" >> "$GITHUB_OUTPUT"
      - id: storeAppID
        name: Store APP ID
        run: |
          echo "APP_ID=MoveStar-API-${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
      
  build:
    runs-on: windows-latest
    needs: configure-vars
    permissions:
      contents: read #This is required for actions/checkout
    env:
      CONFIG : ${{ inputs.CONFIG }}
      NUGET_URL: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    steps:        
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'
          
      - name: Restore
        run: |
          dotnet nuget add source ${{env.NUGET_URL}} --name "github" --username someusername --password ${{secrets.NUGET_TOKEN}}
          dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore --property WarningLevel=1

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs:
      - build
      - configure-vars
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    env:
      API_PATH : ${{ inputs.API_PATH }}
      APP_ID : ${{ needs.configure-vars.outputs.AppID }}
      APP_NAME: ${{ inputs.AZ_APP_NAME }}
      RESOURCE_GROUP : ${{ inputs.RESOURCE_GROUP }}
      SERVICE_NAME : ${{ inputs.SERVICE_NAME }}
      SLOT_NAME : ${{ needs.configure-vars.outputs.FormattedCode }}
      SPEC_PATH : ${{ needs.configure-vars.outputs.SpecPath }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APIM_Client_ID }}
          tenant-id: ${{ secrets.APIM_Tenant_ID }}
          subscription-id: ${{ secrets.APIM_Subscription_ID }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "${{ env.APP_NAME }}"
          slot-name: "${{ env.SLOT_NAME }}"
          package: .
      - name: Update APIM APIs
        run: az apim api import --resource-group "${{ env.RESOURCE_GROUP }}" --service-name "${{ env.SERVICE_NAME }}" --path "${{ env.API_PATH }}" --specification-format OpenApiJson --specification-path "${{ env.SPEC_PATH }}" --api-id "${{ env.APP_ID }}"
