name: 'Build, Pack, Push'
on:
  workflow_call:
    inputs:
      ProjectName:
        required: true
        type: string
      ProjectFolder:
        required: true
        type: string
      Version:
        required: false
        type: string
    secrets:
      NUGET_TOKEN:
        required: true
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: Nuget
    env:
        CONFIG : Release
        NUGET_URL: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        NUGET_TOKEN : ${{ secrets.NUGET_TOKEN }}
        USERNAME : someusername
        SLN: "{{inputs.SlnPath}}"
        PROJECT : "${{ inputs.ProjectName }}"
        PROJECT_FOLDER : "${{ inputs.ProjectFolder }}"
        VERSION : "${{ inputs.Version }}"
        PRERELEASE : ${{ contains(github.ref_name, 'beta') }}
    steps:
      -
        name: Checkout Dashboard
        uses: actions/checkout@v2
      -
        id: GetVersionCode
        run:
          UnformattedVersionCode="${{ env.VERSION }}"
          Formatted="${UnformattedVersionCode/v/""}"
          echo "{VersionCodeFormatted}="{$Formatted} >> $GITHUB_ENV
      -
        run: echo "${{ env.VersionCodeFormatted }}"
